# Generated by Django 3.1.2 on 2021-09-19 18:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CarRentApi', '0003_customer_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=200)),
                ('roomname', models.CharField(max_length=200)),
                ('roomtype', models.CharField(max_length=200)),
                ('roomno', models.IntegerField()),
                ('date', models.DateTimeField()),
                ('price', models.CharField(max_length=20)),
                ('bookTime', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
