# Generated by Django 3.1.2 on 2021-09-19 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CarRentApi', '0004_book'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='bookTime',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='book',
            name='date',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='book',
            name='roomno',
            field=models.CharField(max_length=20),
        ),
    ]
