# Generated by Django 3.1.2 on 2021-09-19 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CarRentApi', '0005_auto_20210920_0133'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='username',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
